# Generated by Django 3.1.5 on 2021-01-05 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_boarduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Time of creation')),
                ('sort_index', models.IntegerField(default=99, verbose_name='Sort index')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.board', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Board column',
                'verbose_name_plural': 'Board columns',
                'db_table': 'board_columns',
            },
        ),
    ]
