# Generated by Django 3.1.5 on 2021-01-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_boardcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Time of creation')),
                ('sort_index', models.IntegerField(default=99, verbose_name='Sort index')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.board', verbose_name='Board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boardcolumn', verbose_name='Board column')),
            ],
            options={
                'verbose_name': 'Board card',
                'verbose_name_plural': 'Board cards',
                'db_table': 'board_cards',
            },
        ),
    ]
